# Generated by Django 3.2 on 2024-10-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с таким email уже существует!'}, max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
