# Generated by Django 3.2 on 2024-10-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='name_not_me',
        ),
    ]
