# Generated by Django 3.2 on 2024-11-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20241029_1037'),
        ('reviews', '0003_auto_20241031_2208'),
    ]

    operations = [
    ]
